# Generated by Django 6.0 on 2025-12-10 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('telegram_id', models.CharField(max_length=255, unique=True, verbose_name='Телеграмм ID')),
                ('phone_number', models.CharField(help_text='Должен быть в формате 998996937308', max_length=255, unique=True, verbose_name='Номер телефона')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('type_of_document', models.CharField(choices=[('Passport', 'Passport'), ('ID Karta', 'ID Karta')], verbose_name='Тип документа')),
                ('card_number', models.CharField(max_length=16, verbose_name='Номер карты')),
                ('card_holder_name', models.CharField(max_length=255, verbose_name='Носитель карты')),
                ('tranzit_number', models.CharField(max_length=255, verbose_name='Транзитный номер')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Наименование банка')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.specialization', verbose_name='Специализация')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
