# Generated by Django 6.0 on 2026-01-03 20:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_absent', models.BooleanField(default=True, help_text='Если работник ЯВИЛСЯ на работу, то надо ОТКЛЮЧТЬ', verbose_name='Отсутсвует')),
                ('start_time', models.TimeField(blank=True, help_text='Когда работник начал рабочий день', null=True, verbose_name='Время начала работы')),
                ('end_time', models.TimeField(blank=True, help_text='Когда работник завершил рабочий день', null=True, verbose_name='Время завершения работы')),
            ],
            options={
                'verbose_name': 'Отметка',
                'verbose_name_plural': 'Отметки',
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.CharField(max_length=255, unique=True, verbose_name='Telegram ID')),
                ('lang', models.CharField(default='uz', max_length=2, verbose_name='Язык')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('born_year', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефона')),
                ('type_of_document', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип документа')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер карты')),
                ('card_holder_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Владелец карты')),
                ('tranzit_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Транзитный номер')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название банка')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специализация')),
                ('id_card_photo1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото ID карты (лицевая сторона)')),
                ('id_card_photo2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото ID карты (обратная сторона)')),
                ('passport_photo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото паспорта')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Работник (Telegram)',
                'verbose_name_plural': 'Работники (Telegram)',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата рабочего дня')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Рабочие дни',
                'db_table': 'days',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Дайте название бригаде', unique=True, verbose_name='Назвние')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Бригада',
                'verbose_name_plural': 'Бригады',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FinishedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, help_text='Пожалуйста, не заполняйте это поле, оно заполниться автоматически', max_length=255, null=True, verbose_name='Название задачи')),
                ('worker_fullname', models.CharField(blank=True, help_text='Пожалуйста, не заполняйте это поле, оно заполниться автоматически', max_length=255, null=True, verbose_name='Работник, который сделал работу')),
                ('description', models.TextField(blank=True, help_text='Необязательное поле', null=True, verbose_name='Описание')),
                ('is_done', models.BooleanField(default=False, verbose_name='Принято')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Завершенная задача',
                'verbose_name_plural': 'Завершенные задачи',
                'ordering': ['-is_done', '-created'],
            },
        ),
        migrations.CreateModel(
            name='FinishedWorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Фото проделанной работы',
                'verbose_name_plural': 'Фото проделанных работ',
            },
        ),
        migrations.CreateModel(
            name='Freshman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('phone_number', models.CharField(help_text='Не принимает больше чем 13 символов, например: +998996937308', max_length=13, verbose_name='Номер телефона')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование объекта')),
                ('service_type', models.CharField(max_length=255, verbose_name='Тип оказываемой услуги')),
                ('responsible_person_details', models.CharField(max_length=255, verbose_name='Данные ответсвенной персоны')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ObjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Фото объекта',
                'verbose_name_plural': 'Фото объекта',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Краткое описание задачи', verbose_name='Название задачи')),
                ('description', models.TextField(help_text='Подробное описание задачи', verbose_name='Описание')),
                ('is_done', models.BooleanField(verbose_name='Завершено')),
                ('deadline', models.DateField(help_text='Дата завершения работы', verbose_name='Дедлайн')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['is_done', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='Foreman',
            fields=[
            ],
            options={
                'verbose_name': 'Бригадир',
                'verbose_name_plural': 'Бригадиры',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ('-created',), 'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='born_year',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_photo1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото ID карты (лицевая часть)'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_photo2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото ID карты (задняя часть)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус активности пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Может ли сотрудник заходить в админ панель', verbose_name='Статус сотрудника'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото пасспорта'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Работник'), ('foreman', 'Бригадир'), ('admin', 'Администратор')], default='worker', max_length=50, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата обновления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название специализации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Статус cуперпользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_of_document',
            field=models.CharField(choices=[('passport', 'Паспорт'), ('id_card', 'ID карта')], max_length=50, verbose_name='Тип документа'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='api_user_phone_n_891aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_id'], name='api_user_telegra_2eeecc_idx'),
        ),
        migrations.AddField(
            model_name='finishedworkphoto',
            name='finished_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.finishedwork', verbose_name='Завершенная работа'),
        ),
        migrations.AddField(
            model_name='freshman',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.specialization', verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='objectphoto',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.object', verbose_name='Завершенная работа'),
        ),
        migrations.AddField(
            model_name='task',
            name='brigades',
            field=models.ManyToManyField(help_text='Бригады, которые будут заниматься задачей', to='api.brigade', verbose_name='Бригады'),
        ),
        migrations.AddField(
            model_name='finishedwork',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_works', to='api.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='object',
            name='workers_involved',
            field=models.ManyToManyField(to='api.worker', verbose_name='Вовлеченные сотруники'),
        ),
        migrations.AddField(
            model_name='finishedwork',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_works', to='api.worker', verbose_name='Работник, который сделал работу'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='workers',
            field=models.ManyToManyField(help_text='Выберите рабочих', related_name='worker_brigade', to='api.worker', verbose_name='Рабочие'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='foreman',
            field=models.OneToOneField(help_text='Выберите бригадира', on_delete=django.db.models.deletion.PROTECT, related_name='brigade', to='api.foreman', verbose_name='Бригадир'),
        ),
    ]
