# Generated by Django 6.0 on 2025-12-10 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_photo1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото ID карты (лицевая часть)'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_photo2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото ID карты (задняя часть)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус активности пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Может ли сотрудник заходить в админ панель', verbose_name='Статус сотрудника'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото пасспорта'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Работник'), ('brigader', 'Бригадир'), ('admin', 'Админ')], default='worker', max_length=50, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата обновления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Статус муперпользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_of_document',
            field=models.CharField(choices=[('passport', 'Passport'), ('id_card', 'ID Karta')], max_length=50, verbose_name='Тип документа'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='api_user_phone_n_891aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_id'], name='api_user_telegra_2eeecc_idx'),
        ),
    ]
