# Generated by Django 6.0 on 2026-01-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attendance_botuser_day_brigade_finishedwork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='born_year',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
