# Generated by Django 5.2.10 on 2026-01-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_born_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigade',
            name='workers',
            field=models.ManyToManyField(blank=True, help_text='Выберите рабочих', related_name='worker_brigade', to='api.worker', verbose_name='Рабочие'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Может ли сотрудник заходить в админ панель', verbose_name='Статус администратора'),
        ),
    ]
