# Generated by Django 6.0 on 2025-12-10 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ('-created',), 'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.specialization', verbose_name='Специализация'),
        ),
    ]
