# Generated by Django 5.2.10 on 2026-02-22 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_brigade_workers_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedwork',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_works', to=settings.AUTH_USER_MODEL, verbose_name='Работник, который сделал работу'),
        ),
    ]
