# Generated by Django 5.2.10 on 2026-04-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_finishedwork_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_for_sending_notifications',
            field=models.BooleanField(default=True, verbose_name='Статус активности пользователя'),
        ),
    ]
