# Generated by Django 6.0 on 2025-12-16 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_specialization_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Дайте название бригаде', unique=True, verbose_name='Назвние')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('foreman', models.OneToOneField(help_text='Выберите бригадира', on_delete=django.db.models.deletion.PROTECT, related_name='foreman_brigade', to=settings.AUTH_USER_MODEL, verbose_name='Бригадир')),
                ('workers', models.ManyToManyField(help_text='Выберите рабочих', related_name='worker_brigades', to=settings.AUTH_USER_MODEL, verbose_name='Рабочие')),
            ],
            options={
                'verbose_name': 'Бригада',
                'verbose_name_plural': 'Бригадs',
                'ordering': ['-created'],
            },
        ),
    ]
