# Generated by Django 6.0 on 2025-12-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_username_brigade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foreman',
            fields=[
            ],
            options={
                'verbose_name': 'Бригадир',
                'verbose_name_plural': 'Бригадиры',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
        ),
        migrations.AlterModelOptions(
            name='brigade',
            options={'ordering': ['-created'], 'verbose_name': 'Бригада', 'verbose_name_plural': 'Бригады'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Работник'), ('foreman', 'Бригадир'), ('admin', 'Админ')], default='worker', max_length=50, verbose_name='Роль'),
        ),
    ]
