# Generated by Django 6.0 on 2025-12-16 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_foreman_alter_brigade_options_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='foreman',
            field=models.OneToOneField(help_text='Выберите бригадира', on_delete=django.db.models.deletion.PROTECT, related_name='brigade', to='api.foreman', verbose_name='Бригадир'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Статус cуперпользователя'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='workers',
            field=models.ManyToManyField(help_text='Выберите рабочих', related_name='worker_brigade', to='api.worker', verbose_name='Рабочие'),
        ),
    ]
