# Generated by Django 6.0 on 2025-12-25 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_born_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_absent', models.BooleanField(default=True, help_text='Если работник ЯВИЛСЯ на работу, то надо ОТКЛЮЧТЬ', verbose_name='Отсутсвует')),
                ('start_time', models.TimeField(blank=True, help_text='Когда работник начал рабочий день', null=True, verbose_name='Время начала работы')),
                ('end_time', models.TimeField(blank=True, help_text='Когда работник завершил рабочий день', null=True, verbose_name='Время завершения работы')),
            ],
            options={
                'verbose_name': 'Отметка',
                'verbose_name_plural': 'Отметки',
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.CharField(max_length=255, unique=True)),
                ('lang', models.CharField(default='uz', max_length=2)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('born_year', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('type_of_document', models.CharField(blank=True, max_length=20, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tranzit_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=20, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('id_card_photo1', models.CharField(blank=True, max_length=255, null=True)),
                ('id_card_photo2', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_photo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Рабочий',
                'verbose_name_plural': 'Рабочие',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата рабочего дня')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Рабочие дни',
                'db_table': 'days',
            },
        ),
        migrations.AlterField(
            model_name='brigade',
            name='foreman',
            field=models.OneToOneField(help_text='Выберите бригадира', on_delete=django.db.models.deletion.PROTECT, related_name='brigade', to='api.botuser', verbose_name='Бригадир'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='workers',
            field=models.ManyToManyField(help_text='Выберите рабочих', related_name='worker_brigade', to='api.botuser', verbose_name='Рабочие'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Краткое описание задачи', verbose_name='Название задачи')),
                ('description', models.TextField(help_text='Подробное описание задачи', verbose_name='Описание')),
                ('is_done', models.BooleanField(verbose_name='Завершено')),
                ('deadline', models.DateField(help_text='Дата завершения работы', verbose_name='Дедлайн')),
                ('brigades', models.ManyToManyField(help_text='Бригады, которые) будут заниматься задачей', to='api.brigade', verbose_name='Бригады')),
            ],
        ),
    ]
