# Generated by Django 6.0 on 2025-12-25 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_attendance_botuser_day_alter_brigade_foreman_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'managed': False, 'verbose_name': 'Рабочий', 'verbose_name_plural': 'Рабочие'},
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'managed': False, 'verbose_name': 'Рабочий день', 'verbose_name_plural': 'Рабочие дни'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='brigade',
            name='foreman',
            field=models.OneToOneField(help_text='Выберите бригадира', on_delete=django.db.models.deletion.PROTECT, related_name='brigade', to='api.foreman', verbose_name='Бригадир'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='workers',
            field=models.ManyToManyField(help_text='Выберите рабочих', related_name='worker_brigade', to='api.worker', verbose_name='Рабочие'),
        ),
    ]
