# Generated by Django 6.0 on 2025-12-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_botuser_options_alter_day_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='brigades',
            field=models.ManyToManyField(help_text='Бригады, которые будут заниматься задачей', to='api.brigade', verbose_name='Бригады'),
        ),
    ]
