# Generated by Django 6.0 on 2025-12-28 12:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_task_description_af_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_done', '-created'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.CreateModel(
            name='FinishedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('worker_fullname', models.CharField(max_length=255, verbose_name='Работник, который сделал работу')),
                ('description', models.TextField(blank=True, help_text='Необязательное поле', null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_works', to='api.task', verbose_name='Задача')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_works', to='api.worker', verbose_name='Работник, который сделал работу')),
            ],
            options={
                'verbose_name': 'Завершенные задачи',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FinishedWorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/', verbose_name='Фото')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('finished_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.finishedwork', verbose_name='Завершенная работа')),
            ],
            options={
                'verbose_name': 'Фото проделанной работы',
                'ordering': ['-created'],
            },
        ),
    ]
