# Generated by Django 6.0 on 2025-12-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_task_options_task_created_task_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finishedwork',
            options={'ordering': ['-is_done', '-created'], 'verbose_name': 'Завершенные задачи'},
        ),
        migrations.AddField(
            model_name='finishedwork',
            name='is_done',
            field=models.BooleanField(default=True, verbose_name='Принять работу'),
        ),
    ]
