# Generated by Django 6.0 on 2025-12-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_finishedwork_options_finishedwork_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedwork',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Принять работу'),
        ),
        migrations.AlterField(
            model_name='finishedwork',
            name='task_name',
            field=models.CharField(blank=True, help_text='Пожалуйста, не заполняйте это поле, оно заполниться автоматически', max_length=255, null=True, verbose_name='Название задачи'),
        ),
        migrations.AlterField(
            model_name='finishedwork',
            name='worker_fullname',
            field=models.CharField(blank=True, help_text='Пожалуйста, не заполняйте это поле, оно заполниться автоматически', max_length=255, null=True, verbose_name='Работник, который сделал работу'),
        ),
    ]
