# Generated by Django 6.0 on 2025-12-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_finishedwork_is_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedwork',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Принято'),
        ),
    ]
