# Generated by Django 6.0 on 2026-01-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_object_objectphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name_uz',
        ),
        migrations.AlterField(
            model_name='finishedworkphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='objectphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото'),
        ),
    ]
