# Generated by Django 6.0 on 2026-01-02 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_task_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название специализации'),
        ),
        migrations.CreateModel(
            name='Freshman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('phone_number', models.CharField(help_text='Не принимает больше чем 13 символов, например: +998996937308', max_length=13, verbose_name='Номер телефона')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
                'ordering': ['-created'],
            },
        ),
    ]
