# Generated by Django 6.0 on 2026-01-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_specialization_name_freshman'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'managed': False, 'verbose_name': 'Работник (Telegram)', 'verbose_name_plural': 'Работники (Telegram)'},
        ),
        migrations.AlterModelOptions(
            name='finishedwork',
            options={'ordering': ['-is_done', '-created'], 'verbose_name': 'Завершенная задача', 'verbose_name_plural': 'Завершенные задачи'},
        ),
        migrations.AlterModelOptions(
            name='finishedworkphoto',
            options={'verbose_name': 'Фото проделанной работы', 'verbose_name_plural': 'Фото проделанных работ'},
        ),
        migrations.AlterField(
            model_name='brigade',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Работник'), ('foreman', 'Бригадир'), ('admin', 'Администратор')], default='worker', max_length=50, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_of_document',
            field=models.CharField(choices=[('passport', 'Паспорт'), ('id_card', 'ID карта')], max_length=50, verbose_name='Тип документа'),
        ),
    ]
